name: DeathMessages
version: ${project.version}
main: net.joshb.deathmessages.DeathMessages
api-version: 1.13
folia-supported: true
softdepend:
  - MythicMobs
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
  - DiscordBotAPI
  - DiscordSRV
  - CombatLogX
author: Joshb_
commands:
  deathmessages:
    description: Main plugin command
  deathmessagestoggle:
    description: Alias for /dm toggle in one command